version: '3.8'
services:
  proxy:
    image: "rhaleem/fdc-event-signup-proxy"
    mem_limit: 128m
    hostname: proxy
    ports:
      - "80:80"
  client:
    image: "rhaleem/fdc-event-signup-client"
    mem_limit: 128m
    hostname: client
  server:
    image: "rhaleem/fdc-event-signup-server"
    mem_limit: 128m
    hostname: server
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT