version: '3.8'
services:
  proxy:
    restart: always
    build:
      context: ./proxy
    depends_on:
      - server
      - client
    ports:
      - '80:80'
  client:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      CHOKIDAR_USEPOLLING: true
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=db
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    depends_on:
      - cache
      - db
  cache:
    image: 'redis:latest'
  db:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password