name: Deploy to AWS Elastic Beanstalk

on:
  workflow_run:
    workflows: ["Build and Push Client CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Create ZIP deployment package
        run: zip -r deploy_package.zip ./
      - 
        name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: "us-east-1"
      - 
        name: Upload package to S3 bucket
        run: aws s3 cp deploy_package.zip s3://fdc-event-signup-code/
      - 
        name: Create new ElasticBeanstalk Application Version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name fdc-event-signup \
          --source-bundle S3Bucket="fdc-event-signup-code",S3Key="deploy_package.zip" \
          --version-label "ver-${{ github.sha }}" \
          --description "commit-sha-${{ github.sha }}"
      - 
        name: Deploy new ElasticBeanstalk Application Version
        run: aws elasticbeanstalk update-environment --environment-name Fdceventsignup-env --version-label "ver-${{ github.sha }}"